# Generated by Django 4.0.10 on 2023-06-28 13:17

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fleetfinder", "0004_fleet_esi_fleet_id_alter_fleet_esi_error_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fleet",
            name="esi_fleet_id",
        ),
    ]
